### ISSUE TITLE
Having trouble connecting to the rcon

### ISSUE THREAD

**Issue by sabinM1** [itzg/docker-rcon-web-admin#12]
Hello,

I have a minecraft server running in a docker container and I can't connect to it via this tool.
![Screenshot from 2021-05-20 18-59-48](https://user-images.githubusercontent.com/46656298/119011299-95d99200-b99d-11eb-972f-5476fe47b40d.png)

I've checked the other issues and tried what I could, but no success.

My docker-compose for the server is:

```
version: "3.8"

services:
  minecraft-server:
    image: "itzg/minecraft-server:multiarch-latest"
    container_name: "mc-pi"
    ports:
      - "25565:25565"
      - "4711:4711"
    volumes:
      - "~/mc/data:/data"
    networks:
      - Minecraft
    environment:
      EULA: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "sabin"
      RCON_PORT: 25575
      TYPE: "PURPUR"
      VERSION: "1.16.5"
      PURPUR_BUILD: "LATEST"
      MEMORY: "1000m"
    tty: true
    stdin_open: true
    restart: always

volumes:
  mc:

networks:
  Minecraft:
```

And the docker-compose for the rcon is:
```
version: "3.8"

services:
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: sabin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: minecraft-server
      RWA_RCON_PASSWORD: sabin
    ports:
      - 4326:4326
      - 4327:4327
    networks:
      - other

networks:
  other:
    external: true
    name: mc_default
```

The folder structure is as follows:
```
.
├── mc
│   ├── data
│   ├── docker-compose.yml
└── rcon
    └── docker-compose.yml
```

Also the docker network:
```
docker network ls
NETWORK ID     NAME              DRIVER    SCOPE
3330c2b424c3   bridge            bridge    local
403bf6ad6186   host              host      local
f4a2d89db847   mc_Minecraft      bridge    local
a7593566ae8d   mc_default        bridge    local
a78b132a0a4a   none              null      local
66d83ced9f93   web               bridge    local
```

```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS                    PORTS                                                                                                 NAMES
481df532f24d   itzg/rcon                                "/usr/local/bin/node…"   14 minutes ago   Up 14 minutes             0.0.0.0:4326-4327->4326-4327/tcp, :::4326-4327->4326-4327/tcp                                         rcon_web_1
5167a15b7446   itzg/minecraft-server:multiarch-latest   "/start"                 18 minutes ago   Up 18 minutes (healthy)   0.0.0.0:4711->4711/tcp, :::4711->4711/tcp, 0.0.0.0:25565->25565/tcp, :::25565->25565/tcp, 25575/tcp   mc-pi
```

Any help is much appreciated! Thanks in advance!
